version: "3.3"
services:
  prisma:
    image: prismagraphql/prisma:1.33
    env_file: ./.env
    restart: always
    depends_on:
      - postgres-db
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: mysecret42
        databases:
          default:
            connector: postgres
            host: postgres-db
            port: 5432
            user: ${DB_USERNAME}
            password: ${DB_PASSWORD}
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  backend:
    restart: on-failure
    build:
      context: ./server
    depends_on:
      - prisma
    volumes:
      - uploads:/app/uploads
    environment:
      PRISMA_ENDPOINT: http://prisma:4466
    command: ["yarn", "start"]
volumes:
  postgres: ~
  uploads: ~
