projects:
  app:
    schemaPath: src/generated/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:6869
  prisma:
    schemaPath: generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
      codegen:
        - generator: prisma-binding
          language: typescript
          output:
            binding: src/generated/prisma.ts
